--- 
version: '3.8'

services:
  prometheus:
    image: prom/prometheus 
    container_name: prometheus_server
    networks:
      - monitoring
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./prometheus_data:/prometheus
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    networks:
      - monitoring
    command:
      - '--path.rootfs=/host'
    ports:
      - 9000:9000
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
  grafana:
    image: grafana/grafana
    container_name: grafana_server
    restart: unless-stopped
    networks:
      - monitoring
    ports:
      - 3000:3000
networks:
  monitoring:
